// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlatformWallet.WebhookDispatcher.Infrastructure.Persistence;

#nullable disable

namespace PlatformWallet.WebhookDispatcher.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WebhookDbContext))]
    [Migration("20260425123006_AddHttpStatusAndResponseBody")]
    partial class AddHttpStatusAndResponseBody
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlatformWallet.WebhookDispatcher.Infrastructure.Persistence.FailedWebhookDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastHttpResponseBody")
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<int?>("LastHttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.ToTable("failed_webhook_deliveries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
